# -*- coding: utf-8 -*-
"""sales_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUEd_UrfV1NdyWXwECA1-z1E5qrKXX-g
"""

import pandas as pd

# Load sales data from CSV
df = pd.read_csv("/Untitled spreadsheet - Sheet1.csv")

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Basic Metrics
total_revenue = df['Revenue'].sum()
total_items_sold = df['Quantity'].sum()
total_orders = len(df)

# Top Selling Products
top_products = df.groupby('Product')['Revenue'].sum().sort_values(ascending=False).head(5)

# Monthly Revenue
df['Month'] = df['Date'].dt.to_period('M')
monthly_revenue = df.groupby('Month')['Revenue'].sum()

# Revenue by Category
category_revenue = df.groupby('Category')['Revenue'].sum()

# Summary Output
print("=== Sales Data Summary ===")
print(f"Total Revenue: ₹{total_revenue}")
print(f"Total Items Sold: {total_items_sold}")
print(f"Total Orders: {total_orders}")
print("\nTop 5 Products:\n", top_products)
print("\nMonthly Revenue:\n", monthly_revenue)
print("\nRevenue by Category:\n", category_revenue)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/Untitled spreadsheet - Sheet1.csv")  # Replace with your file path if needed

print("Sample data:\n", df.head())
print("\nSummary:\n", df.describe())

product_revenue = df.groupby('Product')['Revenue'].sum().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=product_revenue.values, y=product_revenue.index, palette="viridis")
plt.title("Total Revenue by Product")
plt.xlabel("Revenue (₹)")
plt.ylabel("Product")
plt.tight_layout()
plt.show()

category_sales = df.groupby("Category")["Quantity"].sum()
plt.figure(figsize=(6, 6))
plt.pie(category_sales, labels=category_sales.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("pastel"))
plt.title("Sales Quantity by Category")
plt.axis('equal')
plt.show()

df['Date'] = pd.to_datetime(df['Date'])
daily_revenue = df.groupby('Date')['Revenue'].sum().reset_index()

plt.figure(figsize=(12, 5))
sns.lineplot(data=daily_revenue, x='Date', y='Revenue', marker='o')
plt.title("Daily Revenue Trend")
plt.xlabel("Date")
plt.ylabel("Revenue (₹)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()